// Generates the iOS launch ("startup") images and the <link> tags that reference
// them, from the one device table below. Run with `npm run splash`.
//
// Why this exists: an installed iOS web app shows a blank WHITE screen for the whole
// cold-start window unless it is given an apple-touch-startup-image matching the
// device exactly. Every other platform derives a launch screen from the manifest;
// iOS does not.
//
// The images are a flat fill in the app's own background colour, not a logo splash.
// That is deliberate and follows Apple's guidance that a launch screen should
// resemble the app's first frame rather than advertise it: the fill is the same
// colour the <body> paints, so the handoff from launch screen to app is invisible
// instead of a branded card that flashes away.
//
// A flat fill also means no image library. sharp is deliberately absent from this
// project (it has no place on Workers), so the PNGs are written by hand with zlib.
// They compress to a couple of KB each despite the pixel dimensions.
import { deflateSync } from 'node:zlib';
import { writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';

// Portrait CSS width/height + devicePixelRatio. iOS matches these exactly, so an
// unlisted device falls back to white. Add new hardware here and re-run.
const DEVICES = [
  [320, 568, 2, 'iphone-se-1'],
  [375, 667, 2, 'iphone-8'],
  [414, 736, 3, 'iphone-8-plus'],
  [375, 812, 3, 'iphone-x'],
  [414, 896, 2, 'iphone-xr'],
  [414, 896, 3, 'iphone-xs-max'],
  [390, 844, 3, 'iphone-12'],
  [428, 926, 3, 'iphone-12-pro-max'],
  [393, 852, 3, 'iphone-14-pro'],
  [430, 932, 3, 'iphone-14-pro-max'],
  [402, 874, 3, 'iphone-16-pro'],
  [440, 956, 3, 'iphone-16-pro-max'],
];

// Must stay in step with the theme-color metas and the <body> classes:
// slate-50 in light, slate-950 in dark.
const THEMES = { light: '#f8fafc', dark: '#020617' };

const OUT_DIR = 'public/splash';
const LINKS_FILE = 'src/components/SplashLinks.astro';

// ---- a minimal PNG writer (truecolor, no alpha) ----------------------------

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
function crc32(buf) {
  let c = 0xffffffff;
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}
// A one-colour image needs one palette entry, so the pixels are 1 bit each and
// every byte of every scanline is zero. That makes the raw data 24x smaller than
// truecolor before deflate even runs, which is the difference between ~12KB and
// ~1KB per image.
function solidPng(width, height, hex) {
  const rgb = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 1;  // bit depth: 1 bit per pixel
  ihdr[9] = 3;  // colour type 3 = palette
  // 10..12 = compression, filter, interlace: all 0

  // Every scanline is a filter byte (None) followed by all-zero pixel indices.
  const raw = Buffer.alloc((1 + Math.ceil(width / 8)) * height);

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('PLTE', Buffer.from(rgb)),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

// ---- generate --------------------------------------------------------------

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const links = [];
let bytes = 0;

for (const [cssW, cssH, dpr, name] of DEVICES) {
  for (const [theme, hex] of Object.entries(THEMES)) {
    const file = `${name}-${theme}.png`;
    const png = solidPng(cssW * dpr, cssH * dpr, hex);
    writeFileSync(`${OUT_DIR}/${file}`, png);
    bytes += png.length;
    // Light and dark are mutually exclusive, so the order of the tags doesn't
    // matter. Portrait only, matching the manifest's orientation.
    links.push(
      `<link rel="apple-touch-startup-image" href="/splash/${file}"\n` +
      `  media="(device-width: ${cssW}px) and (device-height: ${cssH}px)` +
      ` and (-webkit-device-pixel-ratio: ${dpr})` +
      ` and (orientation: portrait)` +
      ` and (prefers-color-scheme: ${theme})" />`,
    );
  }
}

writeFileSync(LINKS_FILE, `---
// GENERATED by scripts/gen-splash.mjs. Do not edit; run \`npm run splash\`.
//
// iOS launch images for the installed PWA. Without these it shows a blank white
// screen for the whole cold start; each is a flat fill in the app's own background
// colour so the launch screen and the first frame are indistinguishable.
---

${links.join('\n')}
`);

const count = readdirSync(OUT_DIR).length;
console.log(`${count} images, ${(bytes / 1024).toFixed(1)} KB total → ${OUT_DIR}`);
console.log(`${links.length} link tags → ${LINKS_FILE}`);
